name: proxy-access-portal
region: nyc

services:
  - name: web
    github:
      repo: bbarnes4318/proxy
      branch: main
      deploy_on_push: true
    
    source_dir: /
    
    http_port: 8080
    
    environment_slug: python
    
    run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py app:app
    
    envs:
      - key: PORT
        value: "8080"
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    
    instance_count: 1
    instance_size_slug: basic-xxs
    # Memory optimization
    envs:
      - key: GUNICORN_WORKERS
        value: "2"
    
    health_check:
      http_path: /login

