name: proxy-access-portal
region: nyc

services:
  - name: web
    github:
      repo: bbarnes4318/proxy
      branch: main
      deploy_on_push: true
    
    source_dir: /
    
    http_port: 8080
    
    environment_slug: python
    
    run_command: gunicorn --worker-tmp-dir /dev/shm --config gunicorn_config.py app:app
    
    envs:
      - key: PORT
        value: "8080"
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PROXY_HOST
        value: "geo.iproyal.com"
      - key: PROXY_PORT
        value: "12321"
      - key: PROXY_USERNAME
        value: "TmwjTsVQHgTiXElI"
      - key: PROXY_PASSWORD
        value: "Topproducer2026_country-us_city-lasvegas_session-QNpU9Vlz_lifetime-168h"
    
    instance_count: 1
    instance_size_slug: basic-xxs
    # Memory optimization - reduced workers
    envs:
      - key: GUNICORN_WORKERS
        value: "1"
    
    health_check:
      http_path: /health

